### ISSUE TITLE
Infinite $digest Loop

### ISSUE THREAD

**Issue by nishikawa7863** [g00fy-/angular-datepicker#85] opened 2015-03-11 17:13 UTC
I'm trying to use the module in our application, It's working very well I get the following error randomly when using the module:
http://bit.ly/1FbffeO

I think there's some kind of $digest loop, but I haven't been able to isolate it as it happens randomly. You can try it here:

https://surv.es/1b-222f

At the end Birthday is asked and it will throw the error when opening the date picker, any ideas as to what might be causing this issue?

I'm using Chrome 41.0.2272.76 in Mac OS X 10.10.2

**Comment by eralha** [comment] 2015-03-11 17:37
I see the error on console, are you shure its from datepicker module?

Did you try to remove the module? Do you have another watch changing teleData.bDay value?

Can you share some code where you'r handling teleData object?

**Comment by nishikawa7863** [comment] 2015-03-11 18:49
I don't have the error if I remove the module, the only code I use for this inputs is the ng-model directive I don't apply any kind of watch over the teleData object. The only manipulation for this object is done when the slider changes I iterate through the object and and send it through an ajax promise but the original object remains intact.  

Any ideas as to what might be causing this?

Maybe it's crashing with another module but none seems relevant to this case. I'm using:
-ngSanitize
-ngIdle
-geolocation
-ng.deviceDetector
-cfp.hotkeys
-ngDraggable
-angular-carousel
-ngTouch

I'm running out of ideas for the cause of this issue.

**Comment by eralha** [comment] 2015-03-12 14:38
Is the date picker directive watch function that is running on an infinite loop, i can´t figure it out why, i think that is something external, since i can't reproduce this error on a more controlled environment, i need more time to analyse your code.

**Comment by nishikawa7863** [comment] 2015-03-12 18:25
I've tried to isolate it as well with no success, I'm pretty much out of ideas by now. It's very random how the loop takes place. How can I help?

**Comment by eralha** [comment] 2015-03-13 12:33
Can you try implementing this way: http://plnkr.co/edit/94TifOjXZjEAhA25Kl4A?p=preview 
Just for the sake of testing.

**Comment by nishikawa7863** [comment] 2015-03-16 18:50
Yep that code works without problems no error or loops so far.

**Comment by eralha** [comment] 2015-03-17 09:59
My guess is that something is messing with the removing of the datepicker i cant figure out what, if it's ok you can use that code sample to get by this problem.

**Comment by eralha** [comment] 2015-03-25 10:16
Closing...

**Closed by eralha** 2015-03-25 10:16 UTC
